# Generated by Django 4.0.6 on 2022-07-09 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('merchant', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('description', models.TextField(null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('T', 'Transportation'), ('H', 'Housing'), ('F', 'Food'), ('M', 'Miscellaneous')], max_length=3)),
            ],
        ),
    ]
